version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env.local
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - postgres
    networks:
      - bankmanager-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: bankmanager
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bankmanager-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bankmanager-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  bankmanager-network:
    driver: bridge