version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-d3t2br7gi27c73e2adj0-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DB_DATABASE=bankmanager
      - DB_USERNAME=bankmanager_user
      - DB_PASSWORD=rSHM1zdii3hlYfyarGwKvjuvv7EFXwVy
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    networks:
      - bankmanager-network

  # Optional: Local PostgreSQL for development
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bankmanager-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bankmanager-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  bankmanager-network:
    driver: bridge